# Generated by Django 4.2.1 on 2023-05-03 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='hex',
            new_name='color',
        ),
    ]
