# Generated by Django 3.2.16 on 2023-05-03 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_amount_ingredientrecipe_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(flags=0, message='Недопустимый цвет', regex='^#[A-Fa-f0-9]{6}$')], verbose_name='Цвет'),
        ),
    ]
