# Generated by Django 3.2.16 on 2023-05-03 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_tag_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='count',
            new_name='amount',
        ),
    ]
