# Generated by Django 3.2.16 on 2023-05-03 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rename_count_ingredientrecipe_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='units_measurement',
            new_name='measurement_unit',
        ),
    ]
