# Generated by Django 3.2.16 on 2023-05-03 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_rename_units_measurement_ingredient_measurement_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time',
            new_name='cooking_time',
        ),
    ]
