# Generated by Django 3.2.16 on 2023-05-10 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_follow_not_same'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='not_same',
        ),
    ]
